			<div id="panel_content1" style="height: 600px;">
			  	<div class="col-md-5" style="padding-top:150px;position: absolute;top: 0;left: 0;bottom: 0;right: 0;margin: auto;">
			  	
				    <div class="panel panel-default">
				      <div class="panel-heading">Login</div>
				      <div class="panel-body">
				      
	        <?php
			    echo $this->tag->form(
			        array(
			            "admin/auth",
			            "autocomplete" => "off"
			        )
			    );
			?>
							<div class="alert alert-danger" <?php echo $login_alert; ?>>
							  <strong>Invalid </strong> username / password.
							</div>
							
							<div class="form-group">
							  <label for="username">Name:</label>
							  <input type="textarea" class="form-control" id="username" name="username">
							</div>
							<div class="form-group">
							  <label for="password">Password:</label>
							  <input type="password" class="form-control" id="password" name="password">
							</div>
							
							<div class="row">	
				    			<button type="submit" class="btn btn-raised btn-primary center-block" style="width: 200px;">Submit</button>
				    		</div>


		<?php echo $this->tag->endForm(); ?>

			    		
				      </div>
				    </div>
				
				</div>
		    </div>