<div id="panel_content1" style="min-height: 600px;">
<div style="text-align:right;">
	<button type="button" class="btn btn-link" onclick="location.href='logout'">Logout</button>
</div>
<br/>
<div class="panel panel-default">
<div class="panel-heading">External Sites</div>
<div class="panel-body">
<div class="container" style="padding-right: 170px;">
<table class="table table-striped">
	<thead>
		<tr>
			<th style="text-align: center; ">Name</th>
			<th style="text-align: center; ">Key</th>
			<th style="text-align: center; ">Created</th>
			<th style="text-align: center; ">Actions</th>
		</tr>
	</thead>
	<tbody>
	<?php foreach($sites_list as $site){?>
		<tr>
 			<td style="text-align: center; "><?php echo $site['name']; ?></td>
 			<td style="text-align: center; "><?php echo $site['apikey']; ?></td>
 			<td style="text-align: center; "><?php echo $site['timestamp']; ?></td>
 			<td style="text-align: center; "><a href="<?php echo $root_url; ?>admin/deletesite/<?php echo $site['id']; ?>"<span class="glyphicon glyphicon-trash"></span></td>
		</tr>
	<?php } ?>																	
	</tbody>
</table>

<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">Add External Site</button>
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#ChangePasswordModal">Change Admin Password</button>
</div>

</div>
</div>
</div>

<div id="ChangePasswordModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Change Admin Password</h4>
      </div>
      <div class="modal-body">
      
	        <?php
			    echo $this->tag->form(
			        array(
			            "admin/changepassword",
			            "autocomplete" => "off"
			        )
			    );
			?>
			
			  <div class="form-group">
			    <label for="newpassword">New Password:</label>
			    <input type="password" class="form-control" id="newpassword" name="newpassword">
			  </div>
			  <button type="submit" class="btn btn-primary">Submit</button>
		<?php echo $this->tag->endForm(); ?>

      </div>
    </div>

  </div>
</div>


<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Add External Site</h4>
      </div>
      <div class="modal-body">
      
	        <?php
			    echo $this->tag->form(
			        array(
			            "admin/addsite",
			            "autocomplete" => "off"
			        )
			    );
			?>
			
			  <div class="form-group">
			    <label for="sitename">Site Name:</label>
			    <input type="textarea" class="form-control" name="sitename" id="sitename">
			  </div>
			  <button type="submit" class="btn btn-primary">Submit</button>

		<?php echo $this->tag->endForm(); ?>

      </div>
    </div>

  </div>
</div>